#!/bin/bash

[[ -z $KEY ]] && exit 1
[[ -z $ETCDCTL_PEERS ]] && exit 1
[[ -z $FLEETCTL_ENDPOINT ]] && exit 1
[[ -z $FLEETCTL_TUNNEL ]] && exit 1

etcdctl ls /deis_install || etcdctl mkdir /deis_install
etcdctl get /deis_install/complete && exit 0

eval `ssh-agent`

#!/bin/bash

VERSION=${VERSION:=master}

echo -----BEGIN RSA PRIVATE KEY----- > /root/key
echo $KEY | sed 's/-----BEGIN RSA PRIVATE KEY----- //' | sed 's/ -----END RSA PRIVATE KEY-----//' | sed 's/ /\n/g' >> /root/key
echo -----END RSA PRIVATE KEY----- >> /root/key

chmod 0600 /root/key

ssh-add /root/key

cd /root
git clone https://github.com/deis/deis.git
cd deis
git checkout $VERSION
make run && etcdctl set --ttl 0 /deis_install/complete true && etcdctl set --ttl 0 /deis_install/installed_by $ETCDCTL_PEERS
