#!/bin/bash

eval `ssh-agent`

#!/bin/bash

[[ -z $KEY ]] && exit 1

VERSION=${VERSION:=master}

echo -----BEGIN RSA PRIVATE KEY----- > /root/key
echo $KEY | sed 's/-----BEGIN RSA PRIVATE KEY----- //' | sed 's/ -----END RSA PRIVATE KEY-----//' | sed 's/ /\n/g' >> /root/key
echo -----END RSA PRIVATE KEY----- >> /root/key

chmod 0600 /root/key

ssh-add /root/key

cd /root
git clone https://github.com/deis/deis.git
cd deis
git checkout $VERSION
make run
