#!/bin/bash


export FLEETCTL_ENDPOINT=http://${DEIS_HOST}:4001

cd /root 
git clone https://github.com/deis/deis.git 
cd deis

sed -i 's/^.*You need to set FLEETCTL_TUNNEL/######/' includes.mk

make run
